name: "Check for updates"
on:
  schedule:
    #        m  h  d m w
    - cron: "0 */3 * * *"
    # -> run every 3 hours
  push:
permissions:
  contents: write
  pull-requests: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          echo -n "NEW_VERSION=" >> "$GITHUB_ENV"
          nix-shell -p alejandra bun --run 'bun cron' >> "$GITHUB_ENV"
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: bump/bun-v${{ env.NEW_VERSION }}
          commit-message: "bump: Bun -> v${{ env.NEW_VERSION }}"
