name: "Check for updates"
on:
  schedule:
    #        m  h  d m w
    - cron: "0 */3 * * *"
    # -> run every 3 hours
permissions:
  contents: write
  pull-requests: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch latest bun
        run: scripts/cron-update/main.sh
        env:
          AUTO_COMMIT: "true"
          AUTO_CHECKOUT: "true"
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
